apiVersion: v1
kind: PersistentVolume
metadata:
   name: mongo-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
    
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pv-claim
  namespace: rocketchat
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi