apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rocketchat-mongo
  namespace: rocketchat
spec:
  selector:
    matchLabels:
      app: rocketchat-mongo
  serviceName: "rocketchat-mongo-service"
  replicas: 3
  template:
    metadata:
      labels:
        app: rocketchat-mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: mongo:4.0
        ports:
          - containerPort: 27017
        command: ["mongod"]
        args: ["--oplogSize","128","--replSet","rs0","--bind_ip_all"]
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db          
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
             claimName: mongo-pv-claim