apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat-server-deploy
  namespace: rocketchat
  labels:
    app: rocketchat-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketchat-server
  template:
    metadata:
      labels:
        app: rocketchat-server
    spec:
      containers:
      - name: rocketchat-server
        image: rocketchat/rocket.chat:latest
        env:
          - name: PORT
            value: "3000"
          - name: ROOT_URL
            value: "http://localhost:3000"
          - name: MONGO_URL
            value: "mongodb://rocketchat-mongo-service.rocketchat.svc.cluster.local:27017/rocketchat" 
          - name: MONGO_OPLOG_URL
            value: "mongodb://rocketchat-mongo-service.rocketchat.svc.cluster.local:27017/local?replSet=rs0"
        ports:
        - containerPort: 3000


        